spring:
  datasource:
    url: jdbc:mysql://localhost:3306/EmotionGeneration
    username: root
    password: wcc030228
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
huawei:
  obs:
    endpoint: https://obs.cn-south-1.myhuaweicloud.com
    bucket-name: comfyui-e07f
    access-key: IFOTYCFMDVA7SX4ZJ3WD
    secret-key: PmV5L6rhXqzZ53F7DziEW5fxzhIhdTecnYfiv9Sl
app:
  BaseURL: http://localhost:6006/comfyui
  jwt:
   secret: HYOB/tz+Nf5zlMuf17gJCo0DHdUOb5sSWtMHLzYnKxg=
   expiration: 14400000
   #4h 单位为ms

server:
  port: 8080
logging:
  level:
    org.example.expressdeliverysystem: INFO

